import AppSidebar from "@/components/app-sidebar";
import DashboardHeader from "@/components/dashboard-header";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    template: "%s - Cryptokita",
    default: "Home",
  },
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="[--header-height:calc(theme(spacing.14))]"
      suppressHydrationWarning
    >
      <SidebarProvider className="flex flex-col">
        <DashboardHeader />
        <div className="flex flex-1">
          <AppSidebar />
          <SidebarInset>
            <main className="font-[family-name:var(--font-roboto)] flex flex-1 flex-col gap-4 p-4">
              <SidebarTrigger />
              {children}
            </main>
          </SidebarInset>
        </div>
      </SidebarProvider>
    </div>
  );
}
