import Header from "@/components/header";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    template: "%s - Cryptokita",
    default: "Home",
  },
  description: "Generated by create next app",
};
export default function AppLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="font-[family-name:var(--font-roboto)]">
      <Header />
      {children}
    </div>
  );
}
